version: '3'
services:
  db: 
    container_name: dbc
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    ports:
      - 3306:3306
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT}
      MYSQL_USER: ${WORDPRESS_USR}
      MYSQL_PASSWORD: ${WORDPRESS_PASSWD}
volumes: 
  db:
networks:
  app-network:
    
