version: '3.1'
services:
  blog1:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    networks:
      - docker-wordpress-2_app-network      
    environment:
      WORDPRESS_DB_HOST: dbc
      WORDPRESS_DB_USER: ${WORDPRESS_USR}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASSWD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_1}
    volumes:
      - ./blog1:/var/www/html
  blog2:
    image: wordpress
    restart: always
    networks:
      - docker-wordpress-2_app-network          
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: dbc
      WORDPRESS_DB_USER: ${WORDPRESS_USR}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASSWD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_2}
    volumes:
      - ./blog2:/var/www/html
networks:
  docker-wordpress-2_app-network:
    external: true

