CREATE DATABASE <WORDPRESS_DB_1> DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT ALL ON <WORDPRESS_DB_1>.* TO '<WORDPRESS_USR>'@'%';
CREATE DATABASE <WORDPRESS_DB_2> DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT ALL ON <WORDPRESS_DB_2>.* TO '<WORDPRESS_USR>'@'%';
